[[commonly-used-taint-config.adoc]]
include::attributes.adoc[]

= Taint Configuration for Common Vulnerabilities

_Taint Configuration for Common Vulnerabilities_ is a collection of `source`, `sink`, and `transfer` rules tailored for various common vulnerability types.
Currently, this collection contains 327 `source` , 920 `sink`, and 138 `transfer` rules, enabling users to adapt and extend them to detect 13 types of vulnerabilities.


== Organizational structure

We have classified the rules by packages and vulnerability types to help users quickly locate the required ones.
The structure of this project is as follows:

[source]
----
taint-configuration
├── sink
│   ├── infoleak              # contains 141 sinks
│   │   └── java-io
│   └── injection             # contains 779 sinks
│       ├── android
│       │   └── sql-injection
│       ├── java
│       │   ├── crlf
│       │   ├── path-traversal
│       │   ├── rce
│       │   └── ...
│       └── ...
├── source
│   ├── infoleak              # contains 158 sources
│   │   └── java
│   └── injection             # contains 169 sources
│       ├── apache-struts2
│       ├── javax
│       │   ├── javax-portlet
│       │   ├── javax-servlet
│       │   └── javax-swing
│       └── ...
└── transfer                  # contains 138 transfers about String
----

Specifically, this project firstly categorizes the configuration files into three main categories: sink, source, and transfer.

* `sink` category: Contains `sink` configurations files related to information leakage and injection vulnerabilities, further subdivided into two subdirectories:
  ** `infoleak`: Categorized by package name.
  ** `injection`: Categorized by vulnerability type.

* `source` category: Contains `source` configurations related to information leakage and injection vulnerabilities, further subdivided into two subdirectories:
  ** `infoleak`: Categorized by package name.
  ** `injection`: Categorized by package name.

* `transfer` category: Contains commonly used `transfer` configurations.

Additionally, each subdirectory contains a corresponding `README` file that provides a brief overview of the relevant vulnerability types.

== How to Use it? (An Example)


Users can directly integrate the configuration files from this collection into the <<taint-analysis#taint-analysis,Configuration File for the Tai-e taint analysis>>,
or modify and extend them as needed to better meet specific analysis requirements.

Here is an example of how to use the configuration files from this collection.
If the user needs to detect an `RCE (Remote Code Execution)` injection vulnerability in a Java project using the `Jetty` software library, the following steps can be taken to modify the `taint-config.yml` file:

1. Add the `source` rules related to the *Jetty software library* from the file `taint-configuration/source/injection/jetty/jetty-http/jetty-http.yml` to the `taint-config.yml`.
2. Add the `sink` rules related to the *RCE type injection vulnerability* from the file `taint-configuration/sink/injection/java/rce/command.yml` to the `taint-config.yml`.
3. Add the `transfer` rules related to *String type* from the file `taint-configuration/transfer/string-transfers.yml` to the `taint-config.yml`.

Example `taint-config.yml` configuration:

```YAML
source:
  - { kind: call, method: "<org.eclipse.jetty.http.HttpCookie: java.lang.String getName()>", index: result, type: "java.lang.String" }
  - { kind: call, method: "<org.eclipse.jetty.http.HttpCookie: java.lang.String getValue()>", index: result, type: "java.lang.String" }
  - { kind: call, method: "<org.eclipse.jetty.http.HttpCookie: java.lang.String asString()>", index: result, type: "java.lang.String" }
#...

sinks:
  - { method: "<java.lang.Runtime: java.lang.Process exec(java.lang.String)>", index: 0 }
  - { method: "<java.lang.Runtime: java.lang.Process exec(java.lang.String[])>", index: 0 }
  - { method: "<java.lang.Runtime: java.lang.Process exec(java.lang.String, java.lang.String[])>", index: 0 }
#...

transfer:
  - { method: "<java.lang.String: java.lang.String substring(int)>", from: base, to: result }
  - { method: "<java.lang.String: java.lang.String substring(int,int)>", from: base, to: result }
#...
```

