include::attributes.adoc[]

= Publications

* Chenxi Li, Haoran Lin, Tian Tan, and Yue Li. _Two Approaches to Fast Bytecode Frontend for Static Analysis_. In Proceedings of the ACM on Programming Languages, Volume 8, Issue OOPSLA2, Singapore, October 12--18 2025. (OOPSLA'25)

* Yufei Liang, Teng Zhang, Ganlin Li, Tian Tan, Chang Xu, Chun Cao, Xiaoxing Ma, and Yue Li. _Pointer Analysis for Database-Backed Applications_. In Proceedings of the 46th ACM SIGPLAN Conference on Programming Language Design and Implementation, Seoul, South Korea, June 16--20 2025 (PLDI'25).

* Menglong Chen, Tian Tan, Minxue Pan, and Yue Li. _PacDroid: A Pointer-Analysis-Centric Framework for Security Vulnerabilities in Android Apps_. In Proceedings of the 47th IEEE/ACM International Conference on Software Engineering, Ottawa, Canada, April 27--May 3 2025 (ICSE'25).

* Chenxi Zhang, Yufei Liang, Tian Tan, Chang Xu, Shuangxiang Kan, Yulei Sui, and Yue Li. _Interactive Cross-Language Pointer Analysis for Resolving Native Code in Java Programs_. In Proceedings of the 47th IEEE/ACM International Conference on Software Engineering, Ottawa, Canada, April 27--May 3 2025 (ICSE'25).

* Teng Zhang, Yufei Liang, Ganlin Li, Tian Tan, Chang Xu, and Yue Li. _Bridge the Islands: Pointer Analysis for Microservice Systems_. In Proceedings of the 34th ACM SIGSOFT International Symposium on Software Testing and Analysis, Trondheim, Norway, June 25--28 2025 (ISSTA'25).

* Tian Tan and Yue Li. *Tai-e: A Developer-Friendly Static Analysis Framework for Java by Harnessing the Good Designs of Classics*. In Proceedings of the 32nd ACM SIGSOFT International Symposium on Software Testing and Analysis, Seattle, WA, USA. July 17--21, 2023 (ISSTA'23).

* Wenjie Ma, Shengyuan Yang, Tian Tan, Xiaoxing Ma, Chang Xu and Yue Li. _Context Sensitivity without Context: A Cut-Shortcut Approach to Fast and Precise Pointer Analysis_. In Proceedings of the ACM on Programming Languages, 2023 (PLDI'23).

* Tian Tan, Yue Li, Xiaoxing Ma, Chang Xu, and Yannis Smaragdakis. _Making Pointer Analysis More Precise by Unleashing the Power of Selective Context Sensitivity_. In Proceedings of the ACM on Programming Languages, 2021 (OOPSLA'21).

* Yue Li, Tian Tan, Anders Møller, and Yannis Smaragdakis. _A Principled Approach to Selective Context Sensitivity for Pointer Analysis_. ACM Transactions on Programming Languages and Systems, 2020 (TOPLAS'20).

* Yue Li, Tian Tan, and Jingling Xue. _Understanding and Analyzing Java Reflection_. ACM Transactions on Software Engineering and Methodology, 2019 (TOSEM'19).

* Yue Li, Tian Tan, Anders Møller, and Yannis Smaragdakis. _Scalability-First Pointer Analysis with Self-Tuning Context-Sensitivity_. In Proceedings of the 2018 ACM Joint Meeting on European Software Engineering Conference and Symposium on the Foundations of Software Engineering, Lake Buena Vista, FL, USA, November 04-09, 2018 (ESEC/FSE'18).

* Yue Li, Tian Tan, Anders Møller, and Yannis Smaragdakis. _Precision-Guided Context Sensitivity for Pointer Analysis_. Proceedings of the ACM on Programming Languages, 2018 (OOPSLA'18).

* Tian Tan, Yue Li, and Jingling Xue. _Efficient and Precise Points-to Analysis: Modeling the Heap by Merging Equivalent Automata_. In Proceedings of the 38th ACM SIGPLAN Conference on Programming Language Design and Implementation, Barcelona, Spain, June 18-23, 2017 (PLDI'17).

* Tian Tan, Yue Li, and Jingling Xue. _Making k-Object-Sensitive Pointer Analysis More Precise with Still k-Limiting_. In 23rd International Static Analysis Symposium, Edinburgh, UK, September 8-10, 2016, Proceedings (SAS'16).

* Yue Li, Tian Tan, Yifei Zhang, and Jingling Xue. _Program Tailoring: Slicing by Sequential Criteria_. In Proceeding of 30th European Conference on Object-Oriented Programming, July 18-22, 2016, Rome, Italy (ECOOP'16).

* Yue Li, Tian Tan, and Jingling Xue. _Effective Soundness-Guided Reflection Analysis_. In  22nd International Static Analysis Symposium, Saint-Malo, France, September 9-11, 2015, Proceedings (SAS'15).

* Yue Li, Tian Tan, Yulei Sui, and Jingling Xue. _Self-Inferencing Reflection Resolution for Java_. In 28th European Conference, Uppsala, Sweden, July 28 * August 1, 2014. Proceedings (ECOOP'14).
