include::attributes.adoc[]

= How to Specify and Access Types, Classes, and Class Members (Methods and Fields)
Java programs are built using types and classes, which consist of class members such as methods and fields.
Tai-e assigns a unique identifier, known as a signature, to each type, class, and class member.
These signatures enable users to easily configure and specify the behavior of program analyzers for specific elements, such as in taint configuration (see <<taint-analysis#,How to Use Taint Analysis?>>).
Additionally, they allow analysis developers to easily retrieve and manipulate program elements through Tai-e's convenient APIs.

In some cases, it may be necessary to specify _a large number_ of classes or class members within a configuration or when implementing a particular program analysis.
To streamline this process, we have designed and implemented signature wildcards, which allow you to specify multiple classes and class members using a single wildcard signature.

This documentation will guide you through the format of signatures for types, classes, and class members, as well as the APIs for accessing these program elements via their signatures.

NOTE: Since generic types are erased in Java, type signatures, along with class and class member signatures, *do not include type parameters*.

== Type Signatures

=== Class Type

=== Array Type

=== Primitive Type

=== Void Type
* rarely used

=== Obtain A Type via Signature Programmatically

== Class and Class Member Signatures

=== Class Signature

=== Method Signature

* constructor
* class initializer

=== Field Signature

=== Obtain A Class or Member via Signature Programmatically

== Signature Wildcard
