/*
 * Tai-e: A Static Analysis Framework for Java
 *
 * Copyright (C) 2022 Tian Tan <tiantan@nju.edu.cn>
 * Copyright (C) 2022 Yue Li <yueli@nju.edu.cn>
 *
 * This file is part of Tai-e.
 *
 * Tai-e is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * Tai-e is distributed in the hope that it will be useful,but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Tai-e. If not, see <https://www.gnu.org/licenses/>.
 */

package pascal.taie.frontend.java.ir;

import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;

import pascal.taie.ir.exp.DoubleLiteral;
import pascal.taie.ir.exp.Exp;
import pascal.taie.ir.exp.FieldAccess;
import pascal.taie.ir.exp.InvokeExp;
import pascal.taie.ir.exp.Literal;
import pascal.taie.ir.exp.LongLiteral;
import pascal.taie.ir.exp.NullLiteral;
import pascal.taie.ir.exp.Var;
import pascal.taie.ir.stmt.Invoke;
import pascal.taie.ir.stmt.Stmt;
import pascal.taie.language.classes.JMethod;
import pascal.taie.language.type.Type;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Stack;
import java.util.function.Function;


import static pascal.taie.language.type.DoubleType.DOUBLE;
import static pascal.taie.language.type.LongType.LONG;

/**
 * Simulates JVM operand stack during bytecode-to-IR conversion.
 * <p>
 * This class encapsulates all stack manipulation logic,
 * including push/pop operations, expression lifting to variables,
 * and stack safety enforcement.
 */
final class OperandStack {

    /**
     * Sentinel value representing the top half of a double-word value on the stack.
     */
    private static final StackItem TOP = new StackItem(Top.TOP, null);

    /**
     * Phi node list generated by stack merge
     */
    private final List<StackPhi> phiList;

    /**
     * The internal operand stack for the currently processed basic block
     */
    private Stack<StackItem> stack;

    /**
     * The basic block that is currently being processed
     */
    private BytecodeBlock currBlock;

    // --- Dependencies ---
    private final JMethod method;
    private final VarManager varManager;
    private final BytecodeCFG cfg;
    private final StmtManager stmtManager;

    OperandStack(JMethod method, VarManager varManager, BytecodeCFG cfg, StmtManager stmtManager) {
        this.cfg = cfg;
        this.stmtManager = stmtManager;
        this.phiList = new ArrayList<>();
        this.varManager = varManager;
        this.method = method;
    }

    /**
     * Initializes the internal operand stack for the given basic block.
     * <p>
     * This method computes the input stack by merging the output stacks of all
     * predecessor blocks. If the block is a catch handler, the stack remains empty
     * (as per JVM spec, only the exception object is pushed later).
     */
    void initializeStack(BytecodeBlock block) {
        assert stack == null;
        this.currBlock = block;
        stack = new Stack<>();
        if (currBlock.getInStack() == null) {
            computeInStack(currBlock);
        }
        Stack<StackItem> inStack = currBlock.getInStack();
        assert inStack != null || currBlock.isCatch();
        assert currBlock.getOutStack() == null;
        if (!currBlock.isCatch()) {
            stack.addAll(inStack);
        }
    }

    /**
     * Saves the current internal stack as the output stack of the block
     * and resets the internal stack for the next block processing.
     */
    void saveOutStackAndClear() {
        currBlock.setOutStack(stack);
        stack = null;
    }

    /**
     * Returns the list of all StackPhi nodes generated during stack merging.
     */
    List<StackPhi> getStackPhiList() {
        return phiList;
    }

    /**
     * Computes the input stack for a block based on its predecessors in the CFG.
     */
    private void computeInStack(BytecodeBlock block) {
        Stack<StackItem> inStack;
        int inEdgeCount = cfg.getNormalInDegreeOf(block);
        if (cfg.hasNoIncomingNormalEdges(block)) {
            inStack = null;
        } else if (inEdgeCount == 1) {
            BytecodeBlock inEdge = cfg.getNormalPredOf(block, 0);
            assert inEdge.getOutStack() != null;
            inStack = new Stack<>();
            inStack.addAll(inEdge.getOutStack());
        } else {
            inStack = mergeStacks(block, inEdgeCount);
        }
        block.setInStack(inStack);
    }

    /**
     * Merges the output stacks of all predecessor blocks into a single input stack.
     * <p>
     * If different predecessors provide different values for the same stack slot,
     * a {@link StackPhi} node is created to resolve the conflict.
     * Loop headers are handled specially by creating fresh Phis to support cyclic dependencies.
     */
    private Stack<StackItem> mergeStacks(BytecodeBlock block, int inEdgeCount) {
        boolean isLoopHeader = false;
        Stack<StackItem> inStack = null;
        Stack<List<StackItem>> inExpsStack = new Stack<>();
        boolean[] needPhi = null;
        for (int i = 0; i < inEdgeCount; ++i) {
            BytecodeBlock inEdge = cfg.getNormalPredOf(block, i);
            if (inEdge.getOutStack() == null) {
                isLoopHeader = true;
                if (inStack != null) {
                    break;
                }
            } else {
                Stack<StackItem> outStack = inEdge.getOutStack();
                if (inStack == null) {
                    // clone the first non-null stack
                    inStack = new Stack<>();
                    inStack.addAll(outStack);
                    if (isLoopHeader || inStack.isEmpty()) {
                        break;
                    }
                    for (StackItem stackItem : outStack) {
                        List<StackItem> inExps = new ArrayList<>();
                        inExps.add(stackItem);
                        inExpsStack.add(inExps);
                    }
                    needPhi = new boolean[inStack.size()];
                } else {
                    // merge this stack with inStack
                    mergeStack(outStack, inStack, inExpsStack, needPhi);
                }
            }
        }
        assert inStack != null;
        if (isLoopHeader) {
            for (int i = 0; i < inStack.size(); ++i) {
                StackItem item = inStack.get(i);
                Exp e = item.exp();
                if (e instanceof Top) {
                    continue;
                }
                // ignore, add inExpsStack during phi resolving
                inStack.set(i, createNewStackPhi(block, i, new ArrayList<>()));
            }
            block.setLoopHeader();
        } else {
            for (int i = 0; i < inStack.size(); ++i) {
                if (needPhi[i]) {
                    inStack.set(i, createNewStackPhi(block, i, inExpsStack.get(i)));
                }
            }
        }
        return inStack;
    }

    /**
     * Merges a specific predecessor's stack into the accumulating merge state.
     */
    private void mergeStack(Stack<StackItem> outStack, Stack<StackItem> inStack,
                            Stack<List<StackItem>> inExpsStack, boolean[] needPhi) {
        assert inStack.size() == outStack.size();
        for (int j = 0; j < inStack.size(); ++j) {
            StackItem inItem = inStack.get(j);
            Exp inExp = inItem.exp();
            StackItem outItem = outStack.get(j);
            Exp outExp = outItem.exp();
            if (inExp instanceof Top) {
                assert outExp instanceof Top;
                continue;
            }
            List<StackItem> inExps = inExpsStack.get(j);
            inExps.add(outItem);
            assert !(outExp instanceof Top);
            needPhi[j] = needPhi[j] || inExp != outExp;
        }
    }

    /**
     * Creates a new {@link StackPhi} node for a specific stack slot and registers it.
     */
    private StackItem createNewStackPhi(BytecodeBlock block, int index, List<StackItem> inExps) {
        StackPhi phi = new StackPhi(index, inExps, block);
        phi.setVar(varManager.getTempVar());
        varManager.setNonSSA(phi.getVar());
        phiList.add(phi);
        return new StackItem(phi, null);
    }

    /**
     * Pushes expression onto stack, ensuring stack safety for side-effecting expressions.
     */
    void pushExp(AbstractInsnNode node, Exp exp) {
        assert !(exp instanceof Top);
        if (Utils.mayHaveSideEffect(exp)) {
            ensureStackSafety(Utils::mayHaveSideEffect);
        }
        stack.push(new StackItem(exp, node));
        if (isDword(node, exp)) {
            stack.push(TOP);
        }
    }

    /**
     * Pushes a constant onto stack.
     */
    void pushConst(AbstractInsnNode node, Literal literal) {
        if (varManager.peekConstVar(literal)) {
            pushExp(node, varManager.getConstVar(literal));
        } else {
            pushExp(node, literal);
        }
    }

    /**
     * Pops an expression from the stack, skipping Top markers.
     */
    StackItem popExp() {
        StackItem item1 = popStack();
        if (item1.exp() instanceof Top) {
            StackItem item2 = popStack();
            assert !(item2.exp() instanceof Top);
            return item2;
        } else {
            return item1;
        }
    }

    /**
     * Basic pop operation.
     */
    StackItem popStack() {
        return stack.pop();
    }

    /**
     * Pops from stack and ensures the result is a Var.
     */
    Var popVar() {
        StackItem e = popExp();
        liftToVar(e);
        return e.var();
    }

    /**
     * Pops from stack and assigns to the specified variable.
     */
    Stmt popToVar(Var v) {
        StackItem top = popExp();
        if (top.exp() instanceof StackPhi) {
            liftToVar(top);
        } else {
            ensureStackSafety(e -> e == v || e.getUses().contains(v));
        }
        return Utils.newAssignStmt(method, v, top.exp());
    }

    /**
     * Pops from stack for side effects only.
     */
    void popToEffect() {
        StackItem item = popStack();
        Exp e = item.exp();
        if (e instanceof Top) {
        } else {
            expToEffect(item);
        }
    }

    /**
     * Converts expression to side effect statement.
     */
    private void expToEffect(StackItem item) {
        Exp e = item.exp();
        if (e instanceof InvokeExp invokeExp) {
            stmtManager.associateStmt(item.origin(), new Invoke(method, invokeExp));
        } else if (Utils.mayHaveSideEffect(e)) {
            stmtManager.associateStmt(item.origin(),
                    Utils.newAssignStmt(method, varManager.getTempVar(), e));
        }
    }

    void automaticPopToEffect() {
        StackItem item = popExp();
        expToEffect(item);
    }

    /**
     * Ensures the item is a Var, if not, lifts it to a Var.
     * Does nothing for Top. Sets the item.var for Var.
     */
    void liftToVar(StackItem item) {
        Exp exp = item.exp();
        if (exp instanceof Top) {
        } else if (exp instanceof Var var) {
            item.lift(var);
        } else {
            Var var = toVar(exp, item.origin());
            item.lift(var);
        }
    }

    /**
     * Forces lifting to a new Var, even when expression is already a Var.
     * Emits a new ($-v = e) statement.
     */
    private void forceLiftToVar(StackItem item) {
        Var var = toVar(item.exp(), item.origin());
        item.lift(var);
    }

    /**
     * Converts expression to a Var, creating assignment statement if needed.
     */
    Var toVar(Exp e, AbstractInsnNode orig) {
        assert !(e instanceof Var v && varManager.isTempVar(v));
        if (e instanceof StackPhi phi) {
            phi.setUsed();
            assert phi.getVar() != null;
            return phi.getVar();
        }

        Var v;
        if (e instanceof NullLiteral) {
            return varManager.getNullLiteral();
        }
        if (e instanceof Literal l) {
            if (varManager.peekConstVar(l)) {
                return varManager.getConstVar(l);
            } else {
                v = varManager.getConstVar(l);
            }
        } else {
            v = varManager.getTempVar();
        }
        Stmt auxStmt = Utils.newAssignStmt(method, v, e);
        stmtManager.associateStmt(orig, auxStmt);
        return v;
    }

    /**
     * Ensures stack safety by lifting expressions matching the predicate to Vars.
     */
    void ensureStackSafety(Function<Exp, Boolean> predicate) {
        for (StackItem item : stack) {
            Exp exp = item.exp();
            if (exp instanceof Top || exp instanceof StackPhi) {
                continue;
            }
            if (predicate.apply(exp)) {
                forceLiftToVar(item);
            }
        }
    }

    /**
     * Performs JVM stack manipulation operations (DUP, POP, SWAP, etc.).
     */
    void performStackOp(int opcode) {
        switch (opcode) {
            case Opcodes.POP -> popToEffect();
            case Opcodes.POP2 -> {
                popToEffect();
                popToEffect();
            }
            case Opcodes.DUP -> {
                StackItem item = popStack();
                Exp e = item.exp();
                assert !(e instanceof Top);
                liftToVar(item);
                stack.push(item);
                stack.push(item);
            }
            case Opcodes.DUP2 -> dup(2, 0);
            case Opcodes.DUP_X1 -> dup(1, 1);
            case Opcodes.DUP_X2 -> dup(1, 2);
            case Opcodes.DUP2_X1 -> dup(2, 1);
            case Opcodes.DUP2_X2 -> dup(2, 2);
            case Opcodes.SWAP -> {
                StackItem e1 = popStack();
                StackItem e2 = popStack();
                assert !(e1.exp() instanceof Top) && !(e2.exp() instanceof Top);
                stack.push(e1);
                stack.push(e2);
            }
            default -> throw new UnsupportedOperationException();
        }
    }

    /**
     * Performs DUP_X* operations.
     * Takes 'takes' items, skips 'seps' items, then pushes taken items twice.
     */
    private void dup(int takes, int seps) {
        List<StackItem> takesList = new ArrayList<>(takes);
        for (int i = 0; i < takes; ++i) {
            StackItem e = popStack();
            liftToVar(e);
            takesList.add(e);
        }
        Collections.reverse(takesList);
        List<StackItem> sepsList = new ArrayList<>(seps);
        for (int i = 0; i < seps; ++i) {
            sepsList.add(popStack());
        }
        Collections.reverse(sepsList);
        stack.addAll(takesList);
        stack.addAll(sepsList);
        stack.addAll(takesList);
    }

    /**
     * Checks if an expression represents a double-word value (long or double).
     */
    private static boolean isDword(AbstractInsnNode node, Exp e) {
        if (e instanceof InvokeExp invokeExp) {
            Type returnType = invokeExp.getType();
            return returnType == DOUBLE || returnType == LONG;
        } else if (e instanceof LongLiteral || e instanceof DoubleLiteral) {
            return true;
        } else if (e instanceof FieldAccess access) {
            Type fieldType = access.getType();
            return fieldType == DOUBLE || fieldType == LONG;
        } else if (e instanceof Var v && v.isConst()) {
            Literal literal = v.getConstValue();
            return literal instanceof DoubleLiteral || literal instanceof LongLiteral;
        }

        int opcode = node.getOpcode();
        return switch (opcode) {
            case Opcodes.LCONST_0, Opcodes.LCONST_1, Opcodes.DCONST_0, Opcodes.DCONST_1,
                 Opcodes.LLOAD, Opcodes.DLOAD, Opcodes.DALOAD, Opcodes.LALOAD,
                 Opcodes.LADD, Opcodes.DADD, Opcodes.LSUB, Opcodes.DSUB,
                 Opcodes.LMUL, Opcodes.DMUL, Opcodes.LDIV, Opcodes.DDIV,
                 Opcodes.LREM, Opcodes.DREM, Opcodes.DNEG, Opcodes.LNEG,
                 Opcodes.LSHL, Opcodes.LSHR, Opcodes.LUSHR, Opcodes.LAND,
                 Opcodes.LOR, Opcodes.LXOR, Opcodes.I2L, Opcodes.I2D,
                 Opcodes.L2D, Opcodes.F2L, Opcodes.F2D, Opcodes.D2L -> true;
            default -> false;
        };
    }
}
