= Tai-e Documentation Project

The `docs` project produces the Tai-e documentation. It is usually recommended to execute the following commands in the root directory of your project.

== Reference Documentation

To generate the HTML reference documentation, use the following command:

[source,shell,subs="verbatim"]
----
./gradlew :docs:asciidoctor
----

The generated HTML files will be located in `./docs/build/docs/asciidoc/`.

To generate the PDF reference documentation, run the following command:

[source,shell,subs="verbatim"]
----
./gradlew :docs:asciidoctorPdf
----

The generated PDF file will be located in `./docs/build/docs/asciidocPdf/`.

== Javadoc

To generate Javadoc, you can run the following command:

[source,shell,subs="verbatim"]
----
./gradlew :javadoc
----

The generated Javadoc files will be located in `./build/docs/javadoc/`.

== Building all the docs

There is a convenience task available to build all the documentation at once:

[source,shell,subs="verbatim"]
----
./gradlew :docs:all
----

The generated ZIP file containing all the documentation will be located at `./docs/build/tai-e-docs.zip`.
